TERMUX_PKG_VERSION=1.19.1
TERMUX_PKG_SRCURL=https://www.x.org/archive//individual/xserver/xorg-server-$TERMUX_PKG_VERSION.tar.bz2
TERMUX_PKG_SHA256=79ae2cf39d3f6c4a91201d8dad549d1d774b3420073c5a70d390040aa965a7fb
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
--disable-libdrm
--disable-glx
--disable-mitshm
--enable-composite
--enable-xres
--enable-record
--disable-xv
--disable-xvmc
--disable-screensaver
--enable-present
--enable-xinerama
--disable-xace
--disable-dbe
--disable-dpms
--disable-xfree86-utils
--disable-vgahw
--disable-vbe
--disable-int10-module
--disable-pciaccess
--disable-dri
--disable-kdrive-kbd
--disable-input-thread
--disable-glamor
--disable-xf86vidmode
--disable-xf86bigfont
--disable-clientids
--disable-linux-acpi
--disable-linux-apm
--disable-strict-compilation
--disable-listen-tcp
--disable-listen-unix
--disable-listen-linux
--disable-visibility
--disable-xnest
--enable-xquartz
--disable-xwin
--disable-xwayland
--disable-standalone-xpbproxy
--disable-kdrive
--disable-xephyr
--enable-xfake
--enable-xfbdev
--disable-local-transport
--disable-secure-rpc
--enable-input-thread
--enable-xtrans-send-fds
--disable-xorg
--enable-xvfb
--disable-dmx
--enable-ipv6
--enable-tcp-transport
--enable-unix-transport
"
TERMUX_PKG_DEPENDS="libx11, libxfont2, libxkbfile, libxau, libxdmcp, apr"

termux_step_pre_configure () {
	CPPFLAGS="$CPPFLAGS -I$TERMUX_PREFIX/apr-1"
}

